version: 0.2

env:
  variables:
    AWS_REGION: ap-south-2
    IMAGE_REPO_NAME: new-ecr-repo
    CONTAINER_NAME: app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 232818307792.dkr.ecr.ap-south-2.amazonaws.com

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - IMAGE_URI=232818307792.dkr.ecr.ap-south-2.amazonaws.com/new-ecr-repo:$IMAGE_TAG

      - echo Image URI = $IMAGE_URI

  build:
    commands:
      - echo Building Docker image
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $IMAGE_URI

      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
